"""Compatibility exports for the current viewer layer."""

from rnr_mapgen.rendering.viewer import (
    DEFAULT_HEX_RADIUS,
    MAX_ZOOM,
    MIN_ZOOM,
    ViewState,
    axial_round,
    clamp,
    display_to_world,
    format_hover_text,
    hex_to_world,
    map_pixel_bounds,
    nearest_wrapped_world_position,
    polygon_intersects_rect,
    resolve_wrapped_segment,
    run_viewer,
    screen_to_hex_coord,
    world_to_hex,
    world_to_screen,
    world_wrap_width,
    wrapped_copy_offsets,
)

__all__ = [
    "DEFAULT_HEX_RADIUS",
    "MAX_ZOOM",
    "MIN_ZOOM",
    "ViewState",
    "axial_round",
    "clamp",
    "display_to_world",
    "format_hover_text",
    "hex_to_world",
    "map_pixel_bounds",
    "nearest_wrapped_world_position",
    "polygon_intersects_rect",
    "resolve_wrapped_segment",
    "run_viewer",
    "screen_to_hex_coord",
    "world_to_hex",
    "world_to_screen",
    "world_wrap_width",
    "wrapped_copy_offsets",
]
